[tool.poetry]
name = "iam-microservice"
version = "0.0.1"
description = "An Identity Access Manager microservice using FastAPI and an Hexagonal architecture"
authors = ["firminoneto11 <firminoneto11@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
typer = "0.12.*"
sqlalchemy = "2.0.*"
alembic = "1.13.*"
environs = "11.0.*"
fastapi = "0.111.*"

[tool.poetry.group.dev.dependencies]
ruff = "0.4.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
